service: pprofpage
frameworkVersion: "3"

provider:
  name: aws
  stage: ${opt:stage}
  runtime: provided.al2
  architecture: arm64
  region: ap-northeast-1
  apiName: ${self:service}-${self:provider.stage}
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
    HOME: /home/me
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::${self:custom.bucketName}/*'

functions:
  PProfPage:
    handler: bootstrap
    url: true
    timeout: 10
    memorySize: 512
    events:
      - http:
          path: /{proxy+}
          method: any

custom:
  bucketName: shiba6v-pprofpage-${self:provider.stage}
  apigwBinary:
    types:
      - multipart/form-data    # ← バイナリメディアタイプの指定

plugins:
  - serverless-apigw-binary 