services:
  server:
    build:
      context: .
      dockerfile: ./Server.Dockerfile
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - ../..:/server
      - ./gocache:/gocache
    env_file:
      - ./.env
    environment:
      - GOCACHE=/gocache
    command: sh -c "cd /server && air"
  minio:
    image: minio/minio:RELEASE.2022-10-08T20-11-00Z
    container_name: minio
    ports:
      - "9100:9100"
      - "9101:9101"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9100 --console-address :9101"
    volumes:
      - ./minio/data:/export
