service: pprofpage
frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  runtime: provided.al2
  architecture: arm64
  region: ap-northeast-1
  apiName: ${self:service}-${self:provider.stage}
  environment:
    BUCKET_NAME: shiba6v-pprofpage-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::shiba6v-pprofpage-${self:provider.stage}/*'

functions:
  PProfPage:
    handler: bootstrap
    url: true
    timeout: 10
    memorySize: 128
    events:
      - http:
          path: /{proxy+}
          method: any
